### ISSUE TITLE
Move scripts into proper entrypoints

### ISSUE THREAD

**Issue by ephes** [ephes/nyxmon#1]
## Current State

1. We have three scripts in the `scripts/` directory:
   - `add_check.py`: CLI script to add a health check to the database
   - `llm_content.py`: Utility to output code/documentation for LLM context
   - `show_due_checks.py`: CLI script to show all due checks from the database

2. Currently only one entrypoint is defined in `pyproject.toml`:
   ```toml
   [project.scripts]
   start-agent = "nyxmon.entrypoints.cli:start_agent"
   ```

3. The entrypoints directory only contains `cli.py` with the `start_agent` function.

### 1. Refactor scripts into entrypoints

1. Move `add_check.py` functionality to `src/nyxmon/entrypoints/check_management.py`
   - Create a new module to handle check management operations
   - Refactor `add_check_to_db` function

2. Move `show_due_checks.py` functionality to `src/nyxmon/entrypoints/check_management.py`
   - Add `show_due_checks` function to the same module

3. Move `llm_content.py` functionality to `src/nyxmon/entrypoints/developer_tools.py`
   - Create a new module for development/utility tools
   - Refactor the `llm_content` function

### 2. Update `pyproject.toml` with new entrypoints

```toml
[project.scripts]
start-agent = "nyxmon.entrypoints.cli:start_agent"
add-check = "nyxmon.entrypoints.check_management:add_check_to_db"
show-checks = "nyxmon.entrypoints.check_management:show_checks"
llm-content = "nyxmon.entrypoints.developer_tools:llm_content"
```

### 3. Ensure consistent CLI interfaces

- Standardize argument parsing across all commands
- Use consistent error handling and logging 
- Ensure consistent help text and usage examples

## GitHub Issue Checklist

- [x] Create `src/nyxmon/entrypoints/check_management.py` 
- [x] Create `src/nyxmon/entrypoints/developer_tools.py`
- [x] Move `add_check.py` functionality to `check_management.py`
- [x] Move `show_due_checks.py` functionality to `check_management.py`
- [x] Move `llm_content.py` functionality to `developer_tools.py`
- [x] Update `pyproject.toml` with new entrypoints
- [x] Test all CLI commands after migration
- [x] Update documentation to reflect new command names
- [x] Remove original scripts after successful migration...
